version: "3.3"

services:
  www:
    build: .
    container_name: php-apache
    ports: 
      - "2001:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0
    container_name: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: alessandro
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
      - db:db
    ports:
      - 1609:80
    environment:
      PMA_USER: alessandro
      PMA_PASSWORD: password 
  wordpress:
    depends_on: 
      - db
    image: wordpress
    container_name: wordpress
    ports: 
      - 8000:80
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: alessandro
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./www/wp:/var/www/html

volumes:
  db_data: {}
